### ISSUE TITLE
File selection pop-up doesn't show up

### ISSUE THREAD

**Issue by zedascouves** [chungchunwang/Budibase-File-Upload#20]
Hello,

I'm using the plugin's latest version (1.2.0), and Budibase 3.2.3.

Whenever I click the "select file" button, nothing happens. This was working fine while on Budibase 2.*.

Unfortunately, this makes this plugin totally non-functioning.

Please help!

Thank you!

**Comment by rwij86** [comment]
Hi, I’m experiencing the same problem here:

could be caused by a security update on the Budibase server:

Exception:
VM47743:13 a70d1f7a-4772-4323-bf59-b9351b42d16d
app_dev_monoma_39d7f57ba04443b79be6d49b99337ec3#/file-management/documents/addnew:1 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'
https://*.budibase.net
https://cdn.budi.live/
https://js.intercomcdn.com/
https://widget.intercom.io/
https://d2l5prqdbvm3op.cloudfront.net/
https://us-assets.i.posthog.com/
'nonce-yC8Yg82AcWXQWy7nOF8SbQ=='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

explanation: 

The error message you’re seeing relates to a **Content Security Policy (CSP)** set by a web application or server. CSP is a security measure that prevents malicious scripts (such as cross-site scripting, XSS) from being executed on a website. Let’s break it down:

---

### Key Points:
1. **`Refused to execute inline event handler`**  
   The browser is refusing to execute an inline JavaScript event handler. An event handler is a piece of code triggered by an event, such as a button click (`onclick`).

2. **`Content Security Policy directive`**  
   The error refers to the **CSP directives** set by the server. These directives specify which resources (like scripts, styles, etc.) are trusted. In this case, an inline script is not allowed due to security rules.

3. **Requirements According to the CSP**  
   - **`script-src 'self'`**: Only scripts from the same origin as the website (e.g., `https://example.com`) are allowed.
   - **Authorized sources**: Specific domains like `https://*.budibase.net` and `https://cdn.budi.live` are explicitly permitted.
   - **Nonce ('nonce-yC8Yg82AcWXQWy7nOF8SbQ==')**: The server expects inline scripts to include a specific "nonce" (a unique, one-time-use string) to be approved.  
     A nonce is generated by the server and tied to secure scripts.

4. **`unsafe-inline` is missing**  
   To allow inline scripts, the server would need to include the `unsafe-inline` keyword in the CSP directive. However, this is generally avoided as it poses a security risk.

5. **Hashes and `unsafe-hashes`**  
   The error also notes that unless `unsafe-hashes` is explicitly allowed, hashes of scripts (like `sha256-...`) do not apply to event handlers such as `onclick`.

---

### What Does This Mean in Practice?
- **For Developers**:  
  The error indicates that an inline script or event handler (e.g., `onclick="..."`) is attempting to execute, but it’s blocked by the CSP. To resolve this, you can:  
  1. Use external script files instead of inline scripts.  
  2. If inline scripts are necessary, include a nonce that matches the CSP configuration.  
  3. Avoid using inline event handlers whenever possible, and write JavaScript in external files.

- **For End Users**:  
  The error is caused by a configuration issue in the application or server. There’s nothing you can do to fix this yourself, but you can report it to the website administrator.

---
### Conclusion
This error is a security measure to prevent malicious activities. The issue must be resolved by a developer who can adjust the CSP settings or restructure the JavaScript implementation.

look forward for a fix :)

**Comment by chungchunwang** [comment]
Hi! Should be fixed with the new release. It works on my end at least. Feel free to reopen the issue if the problem persist.

**Comment by zedascouves** [comment]
Worked for me as well. 👍 Thank you for the quick fix!

**Comment by rwij86** [comment]
as well 👍  thnx!
